name: CICD

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  workflow_dispatch: 
  
jobs:
  on_build_actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install depencies
        run: |
          cd $GITHUB_WORKSPACE
      - name: Run Tests
        run: python -m unittest unitetsts.py
